version: '3'

services:
  db:
    image: postgres:15
    container_name: intrusion_db
    environment:
      POSTGRES_DB: intrusion_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Kolkata
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  tomcat:
    image: tomcat:9.0
    container_name: intrusion_tomcat
    ports:
      - "8081:8080"
    volumes:
      - ./servlet:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - db